### ISSUE TITLE
feature #3: user can save an artist’s work into their library

### ISSUE THREAD

**Issue by bernardinoa** [bernardinoa/ajax-project#3]
## ⚙️ Feature

user can save an artist’s work into their library

## 📐 Functionality

user will be able to interact with the search functionality and with the respective artwork by being able to add them to a library; the user interaction of clicking the add (plus symbol) button (an indicator that you can add the content into your library) and instantly viewing the transition into a checkmark symbol (an indicator that the artwork was successfully stored in a library)

## 🖼️ Wireframes
![Screen Shot 2021-09-21 at 3 49 54 PM](https://user-images.githubusercontent.com/88168364/134257897-ccd9eecc-5945-45ed-9f63-abc502beff50.png)
![Screen Shot 2021-09-21 at 3 50 02 PM](https://user-images.githubusercontent.com/88168364/134257900-f00e97f4-b6c8-408d-828d-a4b7ac8c893d.png)
![Screen Shot 2021-09-21 at 3 50 13 PM](https://user-images.githubusercontent.com/88168364/134257901-b5863585-2300-427e-a5a7-a0024855b44c.png)
![Screen Shot 2021-09-21 at 3 50 22 PM](https://user-images.githubusercontent.com/88168364/134257904-dbdc66b5-abb1-4b68-bd30-b5bd04bfdf65.png)

## ✅ Task List

- [x] create button on the `card` class, more specifically on the `description` container, which will display the ability to save a piece of artwork and the success of doing so
- [x] get icon `svg`s for plus symbol and checkmark symbol
- [x] create `svg` icons via the dom
- [x] set button to be next to description; style accordingly, i.e., shift description to left, adjust padding, etc
- [x] add view and hidden view to the symbols, i.e., once you click the plus symbol, the plus symbol will hide and the checkmark symbol will show
- [x] think about and implement a feature in the data model where the saved artwork is stored
- [x] replace search icon from fontawesome with an actual search icon `svg` to offload weight; delete the imported fontawesome stylehseet
- [x] make sure that click targets are either `<a>` or `<button>` elements.
- [x] make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **clean up/refactor**
  - [x] remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] remove all console logs.
  - [x] remove all commented out code.
  - [x] remove all CSS properties that have no effect.
  - [x] check all code for proper formatting and indentation.
  - [x] confirm that there are no errors in the console while using the application.
  - [x] confirm that all previous functionality still works without errors.
  - [x] confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
